### PR TITLE
chore(deps): remove deprecated pkg/errors

### PR DESCRIPTION
**Pull request by andig**
Signed-off-by: andig <cpuidle@gmx.de>

## Proposed Changes

Remove deprecated pkg/errors. Depends on https://github.com/influxdata/influxdb-client-go/pull/387, needs rebase/tidy after https://github.com/influxdata/influxdb-client-go/pull/387 has been merged.

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] Tests pass
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Comment by andig** [comment]
Depends on https://github.com/influxdata/influxdb-client-go/pull/387

**Comment by andig** [comment]
Friendly ping- could this be considered for merging?

**Comment by bednar** [comment]
Hi @andig,

the https://github.com/influxdata/influxdb-client-go/pull/387 is merged.

Regards

**Comment by andig** [comment]
Thank you, rebased!

**Review by bednar — CHANGES_REQUESTED** [review]
Thank you for your PR! 👍

Could you please update the CHANGELOG.md with a description of your changes?

**Comment by andig** [comment]
Done

**Review by bednar — APPROVED** [review]

**Pull request merged**
